services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./hotels.json:/docker-entrypoint-initdb.d/hotels.json
    environment:
      - MONGO_INITDB_DATABASE=hotelsdb
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge
